### ISSUE TITLE
Screen not responsive

### ISSUE THREAD

**Issue by PietroMessineo** [illescasDaniel/SideVolumeHUD#1]
I noticed that, when the pop-up of the volume appear the screen is not responsive until the pop-up will disappear. 

Any way for avoid this?

**Comment by illescasDaniel** [comment]
I recently added a tap gesture recognizer so if you tap outside the volume view it will force it to dismiss it with an animation.
I think if you set the animation duration to 0, it will dismiss the volume view immediately and be able to recognize the tap to the views underneath.

**Comment by illescasDaniel** [comment]
Can you confirm this is fixed / works? @PietroMessineo

**Comment by PietroMessineo** [comment]
I can confirm that's working with the tap gesture!
